import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { ReduxProviders } from "./providers/redux";
import AuthProviderLayout from "./providers/sesssion";
import { validateRequest } from "./lib/lucia";
import BarProviders from "./providers/bar";
import { ThemeProvider } from "./providers/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Ubuntu({
  weight: ["400", "500", "700", "300"],
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await validateRequest();
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${font.className} antialiased min-h-screen w-screen`}
        suppressHydrationWarning={true}
      >
        <AuthProviderLayout value={auth}>
          <ReduxProviders>
            <BarProviders>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </BarProviders>{" "}
            <Toaster />
          </ReduxProviders>
        </AuthProviderLayout>
      </body>
    </html>
  );
}
